FROM alpine-java:base
MAINTAINER oopsmails.com
RUN apk --no-cache add netcat-openbsd
COPY files/microservice-docker-service-employee-search-1.0-SNAPSHOT.jar /opt/lib/microservice-docker/microservice-docker-service-employee-search.jar
COPY files/employeeSearch-entrypoint.sh /opt/bin/microservice-docker/
RUN chmod 755 /opt/bin/microservice-docker/employeeSearch-entrypoint.sh

ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/lib/microservice-docker/microservice-docker-service-employee-search.jar"]

EXPOSE 8080
