FROM alpine-java:base
MAINTAINER oopsmails.com
RUN apk --no-cache add netcat-openbsd
COPY files/microservice-docker-service-employee-dashboard-1.0-SNAPSHOT.jar  /opt/lib/microservice-docker/microservice-docker-service-employee-dashboard.jar
COPY files/employeeDashboard-entrypoint.sh /usr/bin/microservice-docker/
RUN chmod 755 /usr/bin/microservice-docker/employeeDashboard-entrypoint.sh
EXPOSE 8081
